# Generated by Django 4.0.2 on 2022-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Население')),
                ('Total_infections', models.PositiveIntegerField(default=0, verbose_name='Всего зараженных')),
                ('Deaths', models.PositiveIntegerField(default=0, verbose_name='Смертельные исходы')),
                ('Recovered', models.PositiveIntegerField(default=0, verbose_name='Выздоровевшие')),
                ('They_are_sick_now', models.PositiveIntegerField(default=0, verbose_name='Болеют прямо сейчас ')),
            ],
            options={
                'verbose_name': 'Данные по Ковиду',
                'verbose_name_plural': 'Данные по Ковиду',
            },
        ),
    ]
